#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerate the embedded 33³ table behind the contributed built-in monitoring look
# (`MonitorLUT.r3dNEMonitor`).
#
# The .cube itself is never committed — `.gitignore` and `just hygiene` both reject `*.cube`
# outside Tests/, and the app has no bundled-asset path (see docs/commit-hygiene.md). The look
# therefore ships as a base64 UInt16 blob inside the shared core, so iOS and Android decode the
# identical table with no per-platform resource plumbing.
#
# Usage: ruby scripts/generate-builtin-lut-table.rb <source.cube>
#
# Prints the FNV-1a 64 checksum of the generated byte stream; the same value is asserted by
# `contributedTableMatchesItsGeneratorChecksum` in Tests/OpenZCineCoreTests/MonitorLUTTests.swift,
# so a regenerated table that differs from the committed one fails the gate instead of shipping.

require 'base64'

TARGET_SIZE = 33
OUTPUT_PATH = File.expand_path('../Sources/OpenZCineCore/MonitorLUTContributedTable.swift', __dir__)
# 88 + the 8 spaces swift-format wants inside the literal stays under the repo's 100-column limit.
BASE64_LINE_WIDTH = 88
BASE64_INDENT = ' ' * 8

abort 'usage: generate-builtin-lut-table.rb <source.cube>' unless ARGV.length == 1
source_path = ARGV[0]
abort "not a file: #{source_path}" unless File.file?(source_path)

# ── Parse the source .cube ────────────────────────────────────────────────────
# Mirrors Sources/OpenZCineCore/CubeLUT.swift `parse`: LUT_3D_SIZE plus red-fastest data triplets,
# comments and metadata skipped. A non-default DOMAIN is rejected rather than silently mismapped.
source_size = nil
values = []
File.foreach(source_path) do |raw|
  line = raw.strip
  next if line.empty? || line.start_with?('#')

  if line.start_with?('LUT_3D_SIZE')
    source_size = Integer(line.split[1])
    next
  end
  if line.start_with?('DOMAIN_MIN', 'DOMAIN_MAX')
    expected = line.start_with?('DOMAIN_MIN') ? 0.0 : 1.0
    components = line.split[1, 3].map(&:to_f)
    abort "unsupported input domain: #{line}" unless components.all? { |c| c == expected }
    next
  end
  next unless line.match?(/\A[-+.\d]/)

  fields = line.split
  next if fields.length < 3

  values.concat(fields[0, 3].map(&:to_f))
end

abort 'source .cube declares no LUT_3D_SIZE' if source_size.nil?
expected_count = source_size**3 * 3
unless values.length == expected_count
  abort "expected #{expected_count / 3} entries, found #{values.length / 3}"
end
puts "parsed #{source_size}³ (#{values.length / 3} entries) from #{File.basename(source_path)}"

# ── Downsample to TARGET_SIZE³ ────────────────────────────────────────────────
# 65 = 2·32 + 1 and 33 = 32 + 1, so every target lattice point lands on an exact source index and
# no interpolation is involved. Any other pair would need trilinear sampling, which would lose
# fidelity silently — so refuse it rather than guess.
step, remainder = (source_size - 1).divmod(TARGET_SIZE - 1)
unless remainder.zero?
  abort "#{source_size}³ does not sample exactly onto #{TARGET_SIZE}³ " \
        "(#{source_size - 1} is not a multiple of #{TARGET_SIZE - 1}); " \
        'trilinear resampling would be required.'
end
puts "exact lattice mapping: every #{TARGET_SIZE}³ point is source index × #{step} (no interpolation)"

samples = []
(0...TARGET_SIZE).each do |b|
  (0...TARGET_SIZE).each do |g|
    (0...TARGET_SIZE).each do |r|
      flat = (r * step) + (g * step * source_size) + (b * step * source_size * source_size)
      samples.concat(values[flat * 3, 3])
    end
  end
end

# ── Quantize to UInt16 and encode ─────────────────────────────────────────────
# ~15 bits per channel. 8 bits bands this look's steep log→display toe (the same reason
# `MonitorLUT.cube` defaults to a 33³ grid), and Float16 would round differently per platform.
bytes = samples.map { |v| (v.clamp(0.0, 1.0) * 65_535).round }.pack('v*')

hash = 0xcbf29ce484222325
bytes.each_byte do |byte|
  hash ^= byte
  hash = (hash * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
end
checksum = format('0x%016x', hash)
grouped = checksum.sub(/\A0x/, '').scan(/.{4}/).join('_')
puts "#{bytes.bytesize} bytes, FNV-1a 64 checksum #{checksum}"

blob = Base64.strict_encode64(bytes)
  .scan(/.{1,#{BASE64_LINE_WIDTH}}/)
  .map { |line| BASE64_INDENT + line }
  .join("\n")

File.write(OUTPUT_PATH, <<~SWIFT)
  // GENERATED FILE — do not edit by hand.
  //
  // Regenerate with:
  //   ruby scripts/generate-builtin-lut-table.rb <somewhere>/R3D_NE_Monitoring_LUT.cube
  //
  // Source: a #{source_size}³ Resolve-exported .cube contributed by Wang Yuehua for inclusion in
  // OpenZCine (see THIRD-PARTY-NOTICES.md). Because #{source_size} = #{step}·#{TARGET_SIZE - 1} + 1,
  // every #{TARGET_SIZE}³ lattice point lands on an exact source index (stride #{step}): these are the
  // contributor's own samples, with no interpolation and so no fidelity lost to the grid change.
  //
  // Encoding: each sample is clamped to 0–1 and stored as a little-endian UInt16 (v · 65535,
  // rounded), then base64'd. The .cube is not committed — `.gitignore` and `just hygiene` reject
  // `*.cube`, and there is no bundled-asset path — so the table travels in the shared core and
  // both shells decode the identical numbers.

  import Foundation

  extension MonitorLUT {
      /// Edge length of the embedded table.
      static let contributedTableSize = #{TARGET_SIZE}

      /// FNV-1a 64 of the decoded byte stream, as printed by the generator.
      static let contributedTableChecksum: UInt64 = 0x#{grouped}

      /// The contributed look's table, decoded once on first use. `map(_:_:_:)` samples it, so the
      /// grid-aligned `cube(size: #{TARGET_SIZE})` reproduces these values exactly.
      static let contributedTableCube: CubeLUT = {
          let bytes = contributedTableBytes()
          let expected = contributedTableSize * contributedTableSize * contributedTableSize * 3
          precondition(
              bytes.count == expected * 2,
              "The embedded contributed LUT table is the wrong size — regenerate it.")
          var rgb = [Float]()
          rgb.reserveCapacity(expected)
          for index in stride(from: 0, to: bytes.count, by: 2) {
              let value = UInt16(bytes[index]) | (UInt16(bytes[index + 1]) << 8)
              rgb.append(Float(value) / 65_535)
          }
          return CubeLUT(size: contributedTableSize, rgb: rgb)
      }()

      /// The decoded little-endian UInt16 stream, before it becomes floats. Exposed so a test can
      /// checksum exactly what the generator hashed.
      static func contributedTableBytes() -> [UInt8] {
          guard
              let data = Data(
                  base64Encoded: contributedTableBase64, options: .ignoreUnknownCharacters)
          else { return [] }
          return [UInt8](data)
      }

      /// FNV-1a 64 — a dependency-free integrity check (Foundation has no digest on every platform
      /// the core builds for, and CryptoKit is Apple-only).
      static func fnv1a64(_ bytes: [UInt8]) -> UInt64 {
          var hash: UInt64 = 0xcbf2_9ce4_8422_2325
          for byte in bytes {
              hash ^= UInt64(byte)
              hash = hash &* 0x100_0000_01b3
          }
          return hash
      }

      static let contributedTableBase64 = """
  #{blob}
          """
  }
SWIFT

puts "wrote #{OUTPUT_PATH.sub(%r{\A.*/Sources/}, 'Sources/')}"
